name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - name: Checkout
      uses: actions/checkout@v2.7.0
      with:
        repository: ${{ github.repository }}

    
    - name: Setup HashiCorp Packer
      # You may pin to the exact commit or the version.
      # uses: hashicorp/setup-packer@ae6b3ed3bec089bbfb576ab7d714df7cbc4b88a4
      uses: hashicorp/setup-packer@v2.0.0
      with:
        # The Packer version to install and add to PATH.
        version: latest
    - name: HashiCorp - Setup Terraform
      # You may pin to the exact commit or the version.
      # uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1
      uses: hashicorp/setup-terraform@v2.0.3
      with:
        # The version of Terraform CLI to install. Instead of full version string you can also specify constraint string starting with "<" (for example `<1.13.0`) to install the latest version satisfying the constraint. A value of `latest` will install the latest version of Terraform CLI. Defaults to `latest`.
        terraform_version: latest
        # Whether or not to install a wrapper to wrap subsequent calls of the `terraform` binary and expose its STDOUT, STDERR, and exit code as outputs named `stdout`, `stderr`, and `exitcode` respectively. Defaults to `true`.
        terraform_wrapper: true
        
    - name: npm install, build and test
      run: |
         cd 01-jenkins-setup/terraform/agent/
         terraform paln
         terraform apply 



