name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - name: Setup HashiCorp Packer
      # You may pin to the exact commit or the version.
      # uses: hashicorp/setup-packer@ae6b3ed3bec089bbfb576ab7d714df7cbc4b88a4
      uses: hashicorp/setup-packer@v2.0.0
      with:
        # The Packer version to install and add to PATH.
        version: latest
    - name: setup eksctl
      run: |
        
      
